apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tech-pr-co-uk-tls
spec:
  secretName: tech-pr-co-uk
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: tech-pr.co.uk
  dnsNames:
    - tech-pr.co.uk
    - www.tech-pr.co.uk
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - tech-pr.co.uk
          - www.tech-pr.co.uk
